### ISSUE TITLE
Deprecate the curated list of dependencies

### ISSUE THREAD

**Issue by cb372** [47degrees/sbt-org-policies#1248]
I think sbt-org-policies is a great idea overall, and does a good job at reducing boilerplate and increasing consistency across our many sbt projects.

But... I really don't like the `%%(...)` feature. I suggest it should be removed, for the following reasons:

* It is confusing to newcomers, especially non-47deg people, who want to contribute to our projects. The first time I encountered this syntax in a build file I had to spend a long time tracking down where it was coming from.
* It confuses scala-steward (I assume), preventing it from keeping our dependencies up to date
* The effort of looking up a library on search.maven.org to find out its organisation name is probably lower than looking it up in [libraries.scala](https://github.com/47deg/sbt-org-policies/blob/aceeffd0a608b63895783e8f9b3a9ec5c611b8e0/core/src/main/scala/sbtorgpolicies/libraries.scala) to see if it is in the curated list.
* Because the list is manually curated, it has inevitably rotted. The library versions are old, and the list of libraries we think people will want to use in their projects is also incomplete and out of date.

**Comment by juanpedromoreno** [comment]
Completed agreed. There is a work in progress towards deprecating most of the sbt-org-policies features like the one you have mentioned. The plugin will be drastically reduced in terms of functionalities, keeping only those things that make more sense, but it's still TBD.
