### ISSUE TITLE
Protected Branches

### ISSUE THREAD

**Issue by juanpedromoreno** [47degrees/sbt-org-policies#263]
When repositories have restrictions to commit on the `master` branch, the plugin will get errors like this:

```
[error] Error committing files
GitHub returned an error: Failed invoking get with status : 422, body : 
 {"message":"3 of 3 required status checks are expected. At least one approved review is required","documentation_url":"https://help.github.com/articles/about-protected-branches"}
```

We should consider to create a PR instead of committing directly to master.

**Comment by andyscott** [comment]
Also, if the bot has administrative access to the repo, it could disable the check temporarily, push the changes, and then reenable the check.

**Comment by juanpedromoreno** [comment]
Good idea, thanks @andyscott , it should be pretty easy to do it:

https://developer.github.com/v3/repos/branches/#enabling-and-disabling-branch-protection
